### ISSUE TITLE
[Leveler] pip dependencies incompatible

### ISSUE THREAD

**Issue by shaikhnedab** [fixator10/Fixator10-Cogs#73]
**Describe the bug**
While installing the `` SciPy`` for ``Leveler cog`` in ``venv`` getting following error:

``ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the 
  source of the following dependency conflicts.``
``red-discordbot 3.4.5 requires attrs==19.3.0, but you have attrs 20.3.0 which is incompatible.``
``red-discordbot 3.4.5 requires Pygments==2.6.1, but you have pygments 2.7.4 which is incompatible.``
``red-discordbot 3.4.5 requires pytz==2020.1, but you have pytz 2020.5 which is incompatible.``

**To Reproduce**
1. Enter Redbot venv
2. Execcute below command
``python -m pip install -U --force-reinstall numpy scipy matplotlib ipython jupyter pandas sympy nose``

**Expected behavior**
Expecting to install " SciPy" without any error.

**Red version**
3.4.5

**Additional context**
I don't know whether it is related to above pip installation issues but I cant change the value of ``!lvladmin msgcredits`` and ``!lvladmin setprice`` both are stuck to``0``.

**Comment by fixator10** [comment]
Dependency conflicts *may*, or *may not* be a problem, if thats really bothers you, or you have any issues with Red caused by that, just reinstall (`python -m pip install -U --force-reinstall red-discordbot`) Red package, otherwise its *usually* not that big of difference, thats more of a warning, then a error.

About additional context: `msgcredits` is disabled for global bank, you need to switch to local bank for it to work. `[p]bankset showsettings` / `[p]bankset toggleglobal`
